# Generated by Django 3.2.5 on 2022-01-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_tasks_snippet_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks_snippet',
            name='due_date',
            field=models.DateField(),
        ),
    ]
