# Generated by Django 3.2.5 on 2022-01-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_tasks_snippet_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks_snippet',
            name='task_details',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
