# Generated by Django 3.2.5 on 2022-01-16 15:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_tasks_snippet_task_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks_snippet',
            name='task_created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
