# Generated by Django 3.2.5 on 2022-01-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_tasks_snippet_task_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks_snippet',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
